name: render all levels

concurrency:
  group: render_all

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run transpiler
      run: dotnet run --project Drizzle.Transpiler/Drizzle.Transpiler.csproj -- LingoSource Drizzle.Ported/Translated
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Render levels
      shell: pwsh
      run: |
        $env:COMPlus_gcServer=1
        dotnet run --no-build -c Release --project Drizzle.ConsoleApp/Drizzle.ConsoleApp.csproj -- render --parallelism 2 (get-childitem -Recurse Data/LevelEditorProjects/*.txt)
